name: Ping Backend Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping https://apifinwell.onrender.com
        run: |
          echo "Pinging backend at https://apifinwell.onrender.com"
          curl -s -o /dev/null -w "%{http_code}" https://apifinwell.onrender.com
